import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import { Montserrat } from "next/font/google";
import ClientSessionProvider from "@/lib/auth/ClientSession";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} text-secondary min-h-screen w-full overflow-x-hidden`}
      >
        <ClientSessionProvider>
          {/* Navbar */}
          <Navbar />

          {children}

          {/* Footer */}
        </ClientSessionProvider>
      </body>
    </html>
  );
}
